### ISSUE TITLE
stoped at downloading

### ISSUE THREAD

**Issue by m1kita** [koron/netupvim#10]
インストール後に最初にアップデートを行ったとき、ダウンロード中に止まりましたので報告します。
ただ、2回目のアップデートは正常に動作しましたので、今のところ再現性はなかったです。

止まった時は、ダウンロード中の28%から動かなくなり、数分経ってもそのままでしたので、cmd.exeのウインドウを閉じました。その後、UPDATE.batをダブルクリックして2回目を行うと、うまく動作しました。

とりあえず、2回分のログファイルを添付します。
[log.zip](https://github.com/koron/netupvim/files/247115/log.zip)

**Comment by koron** [comment]
ありがとうございます。

タイムアウト&エラーが、欲しいですね。

**Comment by koron** [comment]
#11 で何か対策しますので、こちらは閉じます。
