### ISSUE TITLE
空白を含むディレクトリで正常に動作しない

### ISSUE THREAD

**Issue by kariya-mitsuru** [koron/netupvim#14]
netupvim-v1.0b1.zip を C:\Program Files\Vim に展開して UPDATE.BAT を実行したら、C:\Program に新バージョンが取得されました。
なお、試しにコマンドプロンプトから
"c:\Program Files\Vim\netupvim" -t "C:\Program Files\Vim"
を実行したら、正常に C:\Program Files\Vim に新バージョンが取得されました。
UPDATE.BAT ではディレクトリ名に空白を含んでる場合にうまく動作しないようです。
ご対応いただけると助かります。
（すみません、自力ではうまく直せませんでした…）

**Comment by Bakudankun** [comment]
同じ現象が起きました。

バッチファイルの`%TARGET_DIR%`をダブルクォーテーションで囲むだけでは

```
open C:\Program Files\Vim"\vim.exe: The filename, directory name, or volume label syntax is incorrect.
```

というエラーが出ました。
`-t`オプションの引数が`\"`で終わっていると良くない？ようです。

**Comment by koron** [comment]
あら… `os.Args` がおしりに `"` を付けた文字列を返してくるな… もしかして golang ランタイムのバグかな?

**Comment by koron** [comment]
あー `%TARGET_DIR%` が `\` で終わってるから、そのせいで `os.Args` がおかしなことになってるっぽい。

**Comment by koron** [comment]
そしてそのせいで RESTORE.bat も正しく動かない。引数の順番変えるか、カレントディレクトリで制御するか、だなぁ。

**Comment by koron** [comment]
対象ディレクトリを `-t` で指定する方式から、netupvimがもともと持っていたカレントディレクトリを対象とする方式に切り替えます。

**Comment by koron** [comment]
ついでに、PATHに netupvim.exe があるとそっちが優先されちゃうケースへの対応も追加します。

**Comment by koron** [comment]
part of #8
