### ISSUE TITLE
”No such host is known.”というエラーが出ます。PROXY非対応？

### ISSUE THREAD

**Issue by CARBO-Nara-CTP** [koron/netupvim#27]
原因がPROXYなのかどうかわかりませんが、PROXYの中からアクセスしようとしてエラーになります。
PROXYはアクセス時にID/PASSの入力が求められるタイプです。

なお、PROXYがない環境では問題なく動作することを確認しています。

[20160617T180441+0900.log.txt](https://github.com/koron/netupvim/files/320129/20160617T180441.0900.log.txt)

**Comment by koron** [comment]
報告ありがとうございます。
まず間違いなくプロキシ周りです。

対応方法は別途検討しますが、まずはお礼&返答として。

**Comment by koron** [comment]
@CARBO-Nara-CTP [**ココ**](https://github.com/koron/netupvim/commit/5817544248eb2fbdfac36f7b3a80e4e119c1c2ce#diff-04c6e90faac2675aa89e2176d2eec7d8R34) に書いた方法でProxyに渡すユーザー名とパスワードを指定してみてください。

認証ありのプロキシには対応していました。
しかし設定方法の記載がないために使えないということで
ドキュメントを追加してみました。

**Comment by koron** [comment]
ドキュメントの変更はマージしました。

特に何かなければ来週末(25 Jun 2016くらい)までに本issueは閉じます。

**Comment by CARBO-Nara-CTP** [comment]
お返事が遅くなってしまって済みません。
また、迅速なご対応ありがとうございます。

何とかうまくいきましたが、ちょっと課題がございます。
うちの会社はプロキシの設定に自動構成スクリプトを用いているため、どのプロキシを使っているかは普通はわかりません。私は直接スクリプトを解読し、何とか動くようにできましたが、いつスクリプトが変更されるかわかりませんし、このやり方はある程度知識がないと難しいです。

そこでご質問なのですが、プロキシのホストは自動構成スクリプトから入手し、PROXY認証のためのユーザー名とパスワードは環境変数から入手するという方法は難しいのでしょうか？

以上、お手数をおかけしますが、よろしくお願いします。

**Comment by koron** [comment]
netupvim 側で対応する予定はありません。

**Comment by koron** [comment]
http://mattn.kaoriya.net/software/lang/go/20141202173521.htm

これ、今でも有効ならやってもよさげ。

**Comment by koron** [comment]
https://github.com/mattn/go-ieproxy

レジストリからとってきて使ってるだけに見えるから、
自動構成スクリプトの実行結果を取れるわけではなさそう。

**Comment by koron** [comment]
@CARBO-Nara-CTP 検討しましたが、やはりnetupvim自身は自動構成スクリプトには対応しません。

どなたかがそれに対応したパッケージを作成しておられたら、
それを使う形での修正は受け入れる意思があります。

以上、ご期待に添えませんがご容赦ください。

以上、本issueは閉じます。

**Comment by CARBO-Nara-CTP** [comment]
お返事が遅くなってしまいすみません。
色んなソフトが問題なくPROXYつかんで認証のためのダイアログ表示してアクセスできているので、まさか個々のアプリで自動構成スクリプトを解釈しなければいけないことになっているとは思いもよりませんでした。
レジストリを一通り除きましたが、自動構成スクリプトのURLがあるだけだったので、アプリ個々に解釈しているのでしょうね。
IEのAPIか何か叩けば簡単にPROXY情報が入手できるようになっているのかと思っていました。

以上、ご検討ありがとうございました。

**Comment by koron** [comment]
@CARBO-Nara-CTP ある程度、正確なことを補足しておきます。

Windowsにはインターネットに接続する方法が2種類あります。
1つはWinsockで、UNIXなどと同じようにIPソケットを用いて
HTTP以外のプロトコルにも用いられる汎用的な方法です。
もう1つは Wininet で、IEと同じように「ネットワーク接続」の設定を使うのですが、
HTTPなど限られたプロトコルにしかアクセスできない方法です。

golang は前者を用いて実装されています。そのため後者用の設定は機能しないのです。
理論的な可否だけで言えば、もちろんgolangでも後者を利用するようにはできます。
が、私がやるとなると、その労力と得られるものが現時点では釣り合いません。

以上が非対応とした理由です。

**Comment by koron** [comment]
さらに細かい話を補足しておくと…

普通のプロキシの設定だけならば レジストリ を見れば対応できるはず。
ただ 自動構成スクリプト による設定がどうなるかは不明。

**Comment by CARBO-Nara-CTP** [comment]
詳細なご説明ありがとうございます。
とても納得しました。
私個人は取りあえず困っていないので、今のところOKです。

ありがとうございました。
