### ISSUE TITLE
Use conditional requests

### ISSUE THREAD

**Issue by k-takata** [koron/netupvim#30]
API回数制限の対策や、更新がなかったときの高速化のため、`If-Modified-Since` 等の条件リクエストを使うのはどうでしょうか。
https://developer.github.com/v3/#conditional-requests

**Comment by koron** [comment]
渡す時刻は anchor ですかね? 良いと思います!

**Comment by koron** [comment]
go-githubのインターフェースから要修正か～
どういうAPIがええんやろか…

**Comment by k-takata** [comment]
> 渡す時刻は anchor ですかね? 良いと思います!

時刻のフォーマットは修正が必要と思われます。

> どういうAPIがええんやろか…

よく分からなかったのでとりあえずissueだけ立てましたｗ

**Comment by koron** [comment]
> 時刻のフォーマットは修正が必要と思われます。

実は `DirectSource` に関しては
すでに anchor/pivot の値で `If-Modified-Since` で更新チェックしてるので、
そのあたりはバッチシ(CV:清霜)です

**Comment by koron** [comment]
もう超ベタに `LatestIfModifiedSince()` にしようw

**Comment by koron** [comment]
https://github.com/koron/go-github/commit/92fbbed2e046f450922912eb73e5c3f0a67b8b6a#diff-15036d5e0876436b1832c7721c9c7afdR25

こんな感じ。手元の簡単なテストでは、確かにRemainingが減らなくなった。

**Comment by k-takata** [comment]
早い！
go-githubのAPIとしては、`If-None-Match`もサポートしておくと良いかもしれませんね。（使うことあるのか分かりませんが。）

**Comment by koron** [comment]
@k-takata こっちも実装終わりました! テストしてくれると嬉しいかもw

If-None-Matchってことは ETag ですか? なんか良いI/F案があれば、という感じ。
今は超アドホックなんで。

**Comment by koron** [comment]
面倒なのでいきなりmasterにpushしちゃった (ﾃﾍﾍﾟﾛ

**Comment by koron** [comment]
テストどうするべかなぁ

**Comment by koron** [comment]
とりあえず手元のテストは通りました。
golang 1.7beta2だと、ちょっとだめ

**Comment by k-takata** [comment]
こちらでも動作確認できました。

> If-None-Matchってことは ETag ですか? なんか良いI/F案があれば、という感じ。

すみません。今のところ案はありません。

**Comment by koron** [comment]
go1.7beta2 でダメな件は次のissueにしました。
https://github.com/koron/go-arch/issues/2

ということでこっちは閉じます。
