### ISSUE TITLE
setting timeout (question)

### ISSUE THREAD

**Issue by kkdd** [koron/netupvim#37]
timeout 時間を設定して RESTORE.bat を走らせるには、環境変数を設定すれば良いでしょうか？
例えば PowerShell で動かす例としては、下記のようでしょうか？

```ps1
PS> $env:NETUPVIM_DOWNLOAD_TIMEOUT = "1200s"
PS> cmd /c RESTORE.bat
```

**Comment by koron** [comment]
netupvim.ini ファイルに以下の行を追加(ファイルがない場合は作成した上で追加)してみてください。

```toml
DownloadTimeout = "1200s"
```

**Comment by koron** [comment]
`download_timeout` に変わりました。
