### ISSUE TITLE
*-pdb.zip がダウンロードされ、updateできない

### ISSUE THREAD

**Issue by paihu** [koron/netupvim#39]
[20180519T160304+0900.log](https://github.com/koron/netupvim/files/2019205/20180519T160304.0900.log)

**Comment by koron** [comment]
https://github.com/koron/netupvim/blob/9d63000acf7c65407bd13ca03a27f91444646ad1/packages.go#L16
https://github.com/koron/netupvim/blob/9d63000acf7c65407bd13ca03a27f91444646ad1/packages.go#L23

pdb もリリースに含めたことで、ここのパターンが誤爆している。

**Comment by koron** [comment]
キーワードに反応して閉じちゃいましたが、バイナリをリリースしてないので re-open します。

**Comment by koron** [comment]
バイナリリリースは…仕事が一段落したら。

**Comment by koron** [comment]
バイナリをリリースしました。
また復帰方法を https://github.com/koron/netupvim/wiki/Upgrade-Vim-to-8.1 に記載しました。
